"""Added Created data in Grade

Revision ID: 8c6204a3555d
Revises: d6493b2f43be
Create Date: 2024-05-16 18:41:24.293374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6204a3555d'
down_revision = 'd6493b2f43be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'status')
    # ### end Alembic commands ###
